upstream django {
    server django_app:8000;
}

server {
    listen 80;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://django;
    }

    location /static/ {
        alias /app/duchemin/static/;
    }
}

server {
    listen 443 ssl;

    ssl_certificate     /etc/letsencrypt/live/dev.digitalduchemin.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.digitalduchemin.org/privkey.pem;

    if ($ssl_certificate = "") {
        return 444;
    }

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://django;
    }

    location /static/ {
        alias /app/duchemin/static/;
    }

    location ~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}
